# Python package
# Create and test a Python package on multiple Python versions.
# Add steps that analyze code, save the dist with the build record, publish to a PyPI-compatible index, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/python

variables:
  TIME_DURATION: 30d

resources:
  repositories:
  - repository: growth-hacking
    type: github
    name: wso2-enterprise/growth-hacking
    ref: refs/heads/dev-ci *
    endpoint: choreo-cicd *

trigger:
- master

pool:
  vmImage: ubuntu-latest
strategy:
  matrix:
    Python27:
      python.version: '2.7'
    Python35:
      python.version: '3.5'
    Python36:
      python.version: '3.6'
    Python37:
      python.version: '3.7'

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '$(python.version)'
  displayName: 'Use Python $(python.version)'

- script: |
    python -m pip install --upgrade pip
    pip install -r requirements.txt
  displayName: 'Install dependencies'

- script: |
    pip install pytest pytest-azurepipelines
    pytest
  displayName: 'pytest'

- task: AzureCLI@2
  inputs:
    scriptType: 'ps'
    scriptLocation: 'inlineScript'
    inlineScript: 'az monitor app-insights query --app cf464fbd-e3f0-4b0c-970a-c97f178ce338 --analytics-query ''customEvents | where timestamp > ago(30d)'' > data.json'

- task: AzureCLI@1
  displayName: 'Monitoring past data'
  inputs:
    azureSubscription: ''
    scriptLocation: inlineScript
    inlineScript: 'az monitor app-insights query --app cf464fbd-e3f0-4b0c-970a-c97f178ce338 --analytics-query ''customEvents | where timestamp > ago($(TIME_DURATION))'' > data.json'

- task: CmdLine@2
  inputs:
    script: |
      echo Write your commands here
      
      echo Hello world


- task: GitHubComment@0
  inputs:
    gitHubConnection: 'shananjana'
    repositoryName: 'shananjana/python-sample-vscode-flask-tutorial'
    id: '1'
    comment: 'test is running and data is collected'